
'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating a complete full-stack website project from a user prompt.
 *
 * It exports:
 *   - generateFullProject - The main function to trigger the project generation flow.
 *   - GenerateFullProjectInput - The input type for the function.
 *   - GenerateFullProjectOutput - The output type for the function, which is a list of files.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const FileObjectSchema = z.object({
  path: z.string().describe('The full path of the file, including the filename.'),
  content: z.string().describe('The complete content of the file.'),
});

const GenerateFullProjectInputSchema = z.object({
  prompt: z.string().describe('A detailed description of the desired website.'),
  logoDataUri: z.optional(z.string()).describe('Optional: A data URI of a logo to be included and used for theming.'),
  theme: z.optional(z.object({
    primaryColor: z.string(),
    secondaryColor: z.string(),
    accentColor: z.string(),
  })).describe('Optional: A color theme to apply to the website.'),
});
export type GenerateFullProjectInput = z.infer<
  typeof GenerateFullProjectInputSchema
>;

const GenerateFullProjectOutputSchema = z.object({
  files: z
    .array(FileObjectSchema)
    .describe('An array of file objects representing the entire project structure.'),
});
export type GenerateFullProjectOutput = z.infer<
  typeof GenerateFullProjectOutputSchema
>;

export async function generateFullProject(
  input: GenerateFullProjectInput
): Promise<GenerateFullProjectOutput> {
  return generateFullProjectFlow(input);
}

const generateFullProjectPrompt = ai.definePrompt({
  name: 'generateFullProjectPrompt',
  input: {schema: GenerateFullProjectInputSchema},
  output: {schema: GenerateFullProjectOutputSchema},
  prompt: `You are an expert full-stack web developer. The user will describe an application in {{{prompt}}}.

  Based on that description, generate a COMPLETE, PRODUCTION-READY FULL-STACK WEB APPLICATION using Next.js, React, Tailwind CSS, and Firebase.
  
  {{#if logoDataUri}}
  **Logo & Theming Instructions:**
  1.  **Save the Logo:** The user has provided a logo. You MUST save this logo as a file at the path \`src/assets/logo.png\`. The logo is provided as a data URI; decode the Base64 content to create the binary file.
  2.  **Use the Logo Correctly:** In the main layout or header component, you MUST import and display this logo.
      - Use the Next.js <Image> component for this.
      - Import the image like this: \`import logo from '@/assets/logo.png';\`
      - Use it in the component like this: \`<Image src={logo} alt="Logo" width={100} height={40} />\`
  3.  **Apply Theme:** The user has provided a color theme. You MUST update the \`globals.css\` file to use these colors for the CSS variables.
      - Primary Color (for --primary): {{{theme.primaryColor}}}
      - Accent Color (for --accent and --ring): {{{theme.accentColor}}}
  {{/if}}

  **README File Requirement:**
  You MUST include a \`README.md\` file in the root of the project. This file must contain the following content, explaining how to set up and run the project locally.

  \`\`\`md
  # Your Generated Website

  This project was generated by an AI assistant and is a full-stack application built with the following technologies:

  - **Framework:** [Next.js](https://nextjs.org/) (with App Router)
  - **UI:** [React](https://reactjs.org/)
  - **Styling:** [Tailwind CSS](https://tailwindcss.com/)
  - **UI Components:** [ShadCN](https://ui.shadcn.com/)
  - **Backend & Database:** [Firebase](https://firebase.google.com/) (Authentication and Firestore)

  ## Prerequisites

  Before you begin, ensure you have the following installed:
  - [Node.js](https://nodejs.org/) (v18 or later recommended)
  - [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

  ## Step 1: Set up Firebase

  This project requires a Firebase project to handle user authentication and data storage.

  1.  **Create a Firebase Project:** Go to the [Firebase Console](https://console.firebase.google.com/) and create a new project.
  2.  **Enable Authentication:**
      *   In your new project, go to the **Authentication** section.
      *   Click the **Sign-in method** tab.
      *   Enable the **Email/Password** provider and the **Google** provider.
  3.  **Create a Firestore Database:**
      *   Go to the **Firestore Database** section.
      *   Click **Create database** and start in **Production mode**.
      *   Choose a location for your database.
  4.  **Get Firebase Config:**
      *   Go to your **Project Settings** (click the gear icon in the top left).
      *   In the "Your apps" section, create a new **Web app** (</>).
      *   Give it a nickname and register the app.
      *   Firebase will give you a \`firebaseConfig\` object. You will need this for the next step.

  ## Step 2: Configure the Application

  1.  **Create an Environment File:** In the root of this project, create a new file named \`.env.local\`.
  2.  **Add Firebase Credentials:** Paste the keys from your Firebase config object into the \`.env.local\` file like this:

      \`\`\`
      NEXT_PUBLIC_FIREBASE_API_KEY="YOUR_API_KEY"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="YOUR_AUTH_DOMAIN"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID="YOUR_PROJECT_ID"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="YOUR_STORAGE_BUCKET"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="YOUR_SENDER_ID"
      NEXT_PUBLIC_FIREBASE_APP_ID="YOUR_APP_ID"
      \`\`\`

  ## Step 3: Run the Project Locally

  1.  **Install Dependencies:** Open your terminal in the project's root directory and run:
      \`\`\`bash
      npm install
      \`\`\`
  2.  **Start the Development Server:**
      \`\`\`bash
      npm run dev
      \`\`\`
  3.  Open [http://localhost:3000](http://localhost:3000) in your browser to see your website!

  \`\`\`


  STRICT RULES — MUST FOLLOW EXACTLY:
  1.  **Tech Stack:** Use Next.js with the App Router, TypeScript, Tailwind CSS, and Firebase for the backend (Auth and Firestore).
  2.  **Output Format:** You must output a JSON object that strictly conforms to the output schema. The JSON object should contain a single key, "files", which is an array of objects. Each object in the array represents a file and must have two keys: "path" (the full file path) and "content" (the entire file's code).
  3.  **File Structure:** Create a logical and complete file structure for a Next.js project. This includes, but is not limited to:
      - \`README.md\`
      - \`package.json\`
      - \`tailwind.config.ts\`
      - \`next.config.js\`
      - \`tsconfig.json\`
      - \`src/app/layout.tsx\`
      - \`src/app/globals.css\`
      - \`src/app/page.tsx\`
      - \`src/components/ui/...\` (for any ShadCN components)
      - \`src/lib/firebase.ts\` (for Firebase configuration)
      - \`src/app/api/...\` (for any API routes)
  4.  **No Extra Commentary:** Do NOT include any extra explanation, commentary, or markdown formatting in your output. The output must be ONLY the valid JSON object.
  `,
});

const generateFullProjectFlow = ai.defineFlow(
  {
    name: 'generateFullProjectFlow',
    inputSchema: GenerateFullProjectInputSchema,
    outputSchema: GenerateFullProjectOutputSchema,
  },
  async input => {
    const {output} = await generateFullProjectPrompt(input);
    return output!;
  }
);
